Implement JNI wrapper
minmingzhu/oap-mllib pull request #1
Opened 2022-04-07 09:49 UTC by minmingzhu

1. add JNI wrapper
2. modify compiler config
3. add unit test

Signed-off-by: minmingzhu <minming.zhu@intel.com>

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## Does this PR also require the following changes?

- CI
- Documentation
- Example

2022-04-11 13:02 UTC, xwu99 requested changes
I didn't finish review yet, but you can change the code from current comments.

2022-04-12 07:00 UTC, minmingzhu commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/HomogenTableTemplate.java
> +public interface HomogenTableTemplate extends HomogenTableIface{
I refer to oneapi/dal code that homogen_table_impl extends homogen_table_template. You suggest we can move getPullRowsIface and  getPullColumnIface to TableIface/HomogenTableIface and remove HomogenTableTemplate interface?

2022-04-12 11:58 UTC, xwu99 commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/HomogenTableTemplate.java
> +public interface HomogenTableTemplate extends HomogenTableIface{
> I refer to oneapi/dal code that homogen_table_impl extends homogen_table_template. You suggest we can move getPullRowsIface and getPullColumnIface to TableIface or HomogenTableIface and remove HomogenTableTemplate interface?

This class is unnecessary. We don't need to follow the previous interfaces. We can defined interfaces to serve our own needs. I don't like too many level inheritance, If we need more abstraction, we can just refactor in the future.

2022-04-15 02:22 UTC, xwu99 commented
I dont think your tests are running in CI. You may need to remove -Dtest=none from mvn command line.

2022-04-17 06:43 UTC, merged