Make homogen table
minmingzhu/oap-mllib pull request #3
Opened 2022-04-11 06:30 UTC by minmingzhu

## What changes were proposed in this pull request?

1. Convert array ,vector to homogentable.
2. add unit test.

## Does this PR also require the following changes?

- CI
- Documentation
- Example

2022-04-25 05:12 UTC, xwu99 requested changes

2022-04-25 05:12 UTC, xwu99 commented on dev/tools/check-gpu-cpu/check-gpu-cpu.cpp
> +    std::cout << "Checkout GPU!" << std::endl;
```suggestion
    std::cout << "Listing GPU devices ..." << std::endl;
```

2022-04-25 05:12 UTC, xwu99 commented on dev/tools/check-gpu-cpu/check-gpu-cpu.cpp
> +    std::cout << "Checkout CPU!" << std::endl;
```suggestion
    std::cout << "Listing CPU devices ..." << std::endl;
```

2022-04-25 05:12 UTC, xwu99 commented on dev/tools/check-gpu-cpu/Makefile
> +LIBS := -L/usr/local/lib64 -l:libstdc++.a
I don't think it's a good idea to static link to libstdc++. This lib is a system lib, should be linked automatically.

2022-04-25 05:12 UTC, xwu99 commented on dev/tools/check-gpu-cpu/Makefile
> +OUTPUT = check-gpu-cpu
better to rename check-gpu-cpu to list-compute-devices

2022-04-25 05:12 UTC, xwu99 commented on dev/ci/ci-local-dpc-test.sh
> +./test.sh -p CPU_GPU_PROFILE -q
I would not add DEFAULT_HOST_POLICY to build. We will build code for both cpu and gpu devices. 
It should be added to test instead to allow runtime select device. 
I would rename to just "HOST_DEVICE, CPU_DEVICE, GPU_DEVICE", use "-d" for "device".
eg. ./test.sh -p CPU_GPU_PROFILE -d GPU_DEVICE   means run the test for gpu device

2022-04-25 05:12 UTC, xwu99 commented on dev/install-level-zero-ubuntu.sh
> +intel-media-va-driver-non-free libmfx1
intel-media-va-driver-non-free libmfx1 those two packages are related to media driver, why install them?

2022-05-06 06:01 UTC, xwu99 requested changes

2022-05-08 13:58 UTC, minmingzhu commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/HomogenTable.java
> +                        int layoutIndex,
[#4](https://github.com/minmingzhu/oap-mllib/pull/4) PR  has used enum. Thus,  do nothing here.

2022-05-09 01:43 UTC, minmingzhu commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/HomogenTable.java
> +                        int deviceIndex){
https://github.com/minmingzhu/oap-mllib/pull/4 PR has used enum. Thus, do nothing here.

2022-05-09 01:43 UTC, minmingzhu commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/HomogenTable.java
> +                        int deviceIndex){
https://github.com/minmingzhu/oap-mllib/pull/4 PR has used enum. Thus, do nothing here.

2022-05-09 05:31 UTC, merged