Convert homogentable
minmingzhu/oap-mllib pull request #4
Opened 2022-04-17 06:51 UTC by minmingzhu

## What changes were proposed in this pull request?

1. Convert homogentable to array/vector/matrix
2. add unit test

## Does this PR also require the following changes?

- CI
- Documentation
- Example

2022-05-06 06:17 UTC, xwu99 requested changes

2022-05-06 06:17 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/ColumnAccessorImpl.cpp
> +      double* col_doubles = new double[col_values.get_count()];
you don't need to create extra buffer and duplicate col_values. it's a waste for memory transfer.
Could you find if the JNI function you use has some "isCopy" flag to copy the buffer?
Also just dont use new without delete in C++, it's recommanded to use smart pointer.

2022-05-06 06:17 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
>      printf("HomogenTable getcolumncount \n");
could you remove all printf debug if it's unnecessay.

2022-05-09 06:32 UTC, xwu99 commented
@minmingzhu could you rebase to master then I can review this PR.

2022-05-13 01:36 UTC, xwu99 commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/ColumnAccessor.java
> +    private native double[] cPullDouble(long cObject, long cColumnIndex,
Pls put all public interfaces before all private members.

2022-05-13 01:38 UTC, xwu99 commented on mllib-dal/src/main/native/GPU.cpp
> +static sycl::queue *getQue(const sycl::device device) {
```suggestion
static sycl::queue *getSyclQueue(const sycl::device device) {
```

2022-05-13 01:46 UTC, xwu99 commented on mllib-dal/src/main/native/GPU.cpp
> +static sycl::queue *getQue(const sycl::device device) {
pls use refence (sycl::queue &) instead of pointer.

2022-05-13 01:49 UTC, xwu99 commented on mllib-dal/src/main/native/GPU.cpp
> +            new std::shared_ptr<sycl::queue>(queue);
you need to use std::make_shared of C++ library.

2022-05-16 05:41 UTC, minmingzhu commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
>      printf("HomogenTable getcolumncount \n");
I will delete the all printf debug code at the last branch.

2022-05-17 02:07 UTC, xwu99 commented
@minmingzhu  Pls merge the PR. 
and select "Squash and Merge" instead of "Merge pull request"

2022-05-17 03:49 UTC, minmingzhu commented
merge convert_homogentable to dpcpp

2022-05-17 03:52 UTC, merged