Convert RDD[Vector]/RDD[LabeledPoint] to HomogenTable
minmingzhu/oap-mllib pull request #8
Opened 2022-05-18 07:50 UTC by minmingzhu

## What changes were proposed in this pull request?

1. convert RDD[Vector]/RDD[LabeledPoint] to HomogenTable
2. add unit test

## Does this PR also require the following changes?

- CI
- Documentation
- Example

2022-05-19 08:49 UTC, xwu99 requested changes

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +      homogenPtr tablePtr = std::make_shared<homogen_table>(*h_table);
Line 431-432 can be merged into single one. 
std::make_shared is to new the object and make share_ptr at the same time

```suggestion
      homogenPtr tablePtr = std::make_shared<homogen_table>();
```

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +      homogenPtr tablePtr = std::make_shared<homogen_table>(*h_table);
Line 431-432 can be merged into single one. 
std::make_shared is to new the object and make share_ptr at the same time

```suggestion
      homogenPtr tablePtr = std::make_shared<homogen_table>();
```

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +              homogenPtr resultTablePtr = std::make_shared<homogen_table>(*resultTable);
Same as above, should not use new.
```suggestion
              homogenPtr resultTablePtr = std::make_shared<homogen_table>(row_doubles, cRowCount, cColCount, detail::empty_delete<const double>());
```
```suggestion
              homogenPtr resultTablePtr = std::make_shared<homogen_table>(*resultTable);
```

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +              homogenPtr resultTablePtr = std::make_shared<homogen_table>(*resultTable);
Same as above, should not use new.
```suggestion
              homogenPtr resultTablePtr = std::make_shared<homogen_table>(row_doubles, cRowCount, cColCount, detail::empty_delete<const double>());
```
```suggestion
              homogenPtr resultTablePtr = std::make_shared<homogen_table>(*resultTable);
```

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +              double* row_doubles = new double[mergeDatasize + homogenDatasize];
should not use new

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +              double* row_doubles = new double[mergeDatasize + homogenDatasize];
should not use new

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/RowAccessor.java
>          this.cDevice =device;
```suggestion
        this.cDevice = device;
```

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/java/com/intel/oneapi/dal/table/RowAccessor.java
>          this.cDevice =device;
```suggestion
        this.cDevice = device;
```
```suggestion
        this.cDevice =device;
```

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +    homogenPtr tablePtr;
there are code duplication below. pls refactor.

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/HomogenTableImpl.cpp
> +    homogenPtr tablePtr;
there are code duplication below. pls refactor.

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/OneDAL.scala
> +        mergedLabels.addHomogenTable(labelAddr)
If the merging copied discrete buffer into continious buffer, the original buffer should be released to save memory.

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/main/scala/com/intel/oap/mllib/OneDAL.scala
> +        mergedLabels.addHomogenTable(labelAddr)
If the merging copied discrete buffer into continious buffer, the original buffer should be released to save memory.

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/test/scala/com/intel/oap/mllib/ConvertHomogenTableSuite.scala
>      assert(expectData=== vector.toArray)
should use assertArrayEquals?

2022-05-19 08:49 UTC, xwu99 commented on mllib-dal/src/test/scala/com/intel/oap/mllib/ConvertHomogenTableSuite.scala
>      assert(expectData=== vector.toArray)
should use assertArrayEquals?

2022-05-25 05:32 UTC, minmingzhu commented on mllib-dal/src/test/scala/com/intel/oap/mllib/ConvertHomogenTableSuite.scala
>      assert(expectData=== vector.toArray)
Scala has not assertArrayEquals function.

2022-05-25 05:32 UTC, minmingzhu commented on mllib-dal/src/test/scala/com/intel/oap/mllib/ConvertHomogenTableSuite.scala
>      assert(expectData=== vector.toArray)
Scala has not assertArrayEquals function.

2022-05-26 01:25 UTC, xwu99 requested changes

2022-05-26 01:25 UTC, xwu99 commented on mllib-dal/src/main/native/oneapi/dal/SimpleMetadataImpl.cpp
> +    table_metadata mdata = *((table_metadata *)cTableAddr);
could you use c++ style type casting (reinterpret_cast/static_cast etc.)? same for other places.

2022-05-26 01:25 UTC, xwu99 commented on mllib-dal/src/test/scala/org/apache/spark/ml/oneDALSuite.scala
> +        case "HOST" =>  computeDevice = Common.ComputeDevice.HOST
```suggestion
        case "HOST" => computeDevice = Common.ComputeDevice.HOST
```

2022-05-26 01:25 UTC, xwu99 commented on mllib-dal/src/test/scala/org/apache/spark/ml/oneDALSuite.scala
> +        case "CPU"  => computeDevice = Common.ComputeDevice.CPU
```suggestion
        case "CPU" => computeDevice = Common.ComputeDevice.CPU
```

2022-05-26 01:25 UTC, xwu99 commented on mllib-dal/src/test/scala/org/apache/spark/ml/oneDALSuite.scala
> +        case "GPU"  => computeDevice = Common.ComputeDevice.GPU
```suggestion
        case "GPU" => computeDevice = Common.ComputeDevice.GPU
```

2022-05-26 01:25 UTC, xwu99 commented on mllib-dal/src/test/scala/org/apache/spark/ml/oneDALSuite.scala
> +        case _  => "Invalid Device"
```suggestion
        case _ => "Invalid Device"
```

2022-05-26 01:25 UTC, xwu99 commented on mllib-dal/src/test/scala/com/intel/oap/mllib/ConvertHomogenTableSuite.scala
>      assert(expectData=== vector.toArray)
this is a JUnit function, you should be able to use it in Scala

2022-05-31 02:40 UTC, merged

2022-06-01 03:11 UTC, xwu99 commented
Thanks, could you rebase #7 and I will review it. thanks!